dist: trusty
language: cpp

notifications:
  email:
    recipients:
      - 0f9234u9f0jw3@gmx.de
    on_success: always
    on_failure: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      
script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 bash ./build.sh Debug 
  - cd ./Debug
  - ctest --verbose .

