image:
  - Visual Studio 2015
clone_folder: C:\philslib

build_script:
- cmd: >-
    cd C:\philslib
    
    bitsadmin.exe /transfer "doctest" "https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h" "C:\philslib\test\doctest.h"
        
    build.bat "Visual Studio 14" "Debug"
    
test: on
test_script:
  - cmd: >-
      ctest --verbose C:\philslib\Debug

