image:
  - Visual Studio 2015
clone_folder: C:\philslib

build_script:
- cmd: >-
    cd C:\philslib
            
    build.bat "Visual Studio 14 Win64" Debug x64
    
test: on
test_script:
  - cmd: >-
      cd C:\philslib\Debug_x64
  
      ctest --verbose .
      
      cd ..

