image:
  - Visual Studio 2015
clone_folder: C:\philslib

build_script:
- cmd: >-
    cd C:\philslib
            
    build.bat "Visual Studio 14" Debug
    
test: on
test_script:
  - cmd: >-
      cd C:\philslib\Debug
  
      ctest --verbose .
      
      cd ..

