image:
  - Visual Studio 2015
clone_folder: C:\philslib

build_script:
- cmd: >-
    cd C:\philslib
    
    bitsadmin.exe /transfer "doctest" "https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctes
t.h" "C:\philslib\test\doctest.h"
    
    cmake -G "Visual Studio 14" C:\philslib
    
    cmake --build C:\philslib
    
test: on
test_script:
  - cmd: >-
      ctest --verbose C:\philslib

